using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WebInterface.Models
{

    public class Guest
    {
        public int GuestID { get; set; }

        /// <summary>
        /// The code of a guest is used to ensure that 2 guests cannot use each others pages by guessing their ID.
        /// This code should be generated by the static GenerateGuestCode method in the Guest class.
        /// </summary>
        [StringLength(128)]
        public string Code { get; set; }



         // <summary>
         // The age of the customer.
        // </summary>
         
        public string Name { get; set; }
        // <summary>
        /// The group wo which this guest belongs.
        /// A guest should be created when he or she scans 
        /// a QR code. At that time the table is know, hence 
        /// the current group, hence a Guest can always 
        /// belongs to a specific group.
        /// </summary>
        public virtual Group Group { get; set; }

        #region helpers
        private static Random rand = new Random();

        /// <summary>
        /// Generates a GuestCode that is unique for every unique GuestID.
        /// Note that running this method twice on the same GuestID may result in two different GuestCodes.
        /// This is not a hashing function!
        /// 
        /// The code is generated by appending the guestID by 64 additional digits.
        /// </summary>
        /// <param name="guestID"></param>
        /// <returns></returns>
        public static string GenerateGuestCode(int guestID)
        {
            StringBuilder str = new StringBuilder();
            str.Append(guestID.ToString());

            for(int i = 0; i < 64; i++)
            {
                str.Append(rand.Next(10));
            }

            return str.ToString();
        }

        #endregion
    }
}
