// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebInterface.Models;

namespace WebInterface.Data.Migrations
{
    [DbContext(typeof(MenuCardDBContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebInterface.Models.Bill", b =>
                {
                    b.Property<int>("BillID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("PayerGuestID");

                    b.HasKey("BillID");

                    b.HasIndex("PayerGuestID");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("WebInterface.Models.Dish", b =>
                {
                    b.Property<int>("DishID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("OrderID");

                    b.Property<int?>("OrderID1");

                    b.Property<int?>("TypeDishTypeID");

                    b.HasKey("DishID");

                    b.HasIndex("OrderID");

                    b.HasIndex("OrderID1");

                    b.HasIndex("TypeDishTypeID");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("WebInterface.Models.DishType", b =>
                {
                    b.Property<int>("DishTypeID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Type");

                    b.HasKey("DishTypeID");

                    b.ToTable("DishTypes");
                });

            modelBuilder.Entity("WebInterface.Models.Group", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("HidePrice");

                    b.Property<int?>("TableID");

                    b.HasKey("GroupID");

                    b.HasIndex("TableID")
                        .IsUnique()
                        .HasFilter("[TableID] IS NOT NULL");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("WebInterface.Models.Guest", b =>
                {
                    b.Property<int>("GuestID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GroupID");

                    b.Property<string>("Name");

                    b.HasKey("GuestID");

                    b.HasIndex("GroupID");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("WebInterface.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DishID");

                    b.Property<int?>("DishTypeID");

                    b.Property<double>("Quantity");

                    b.Property<int?>("TypeIngredientTypeID");

                    b.HasKey("IngredientID");

                    b.HasIndex("DishID");

                    b.HasIndex("DishTypeID");

                    b.HasIndex("TypeIngredientTypeID");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("WebInterface.Models.IngredientType", b =>
                {
                    b.Property<int>("IngredientTypeID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("UnitPlural");

                    b.Property<string>("UnitSingular");

                    b.HasKey("IngredientTypeID");

                    b.ToTable("IngredientTypes");
                });

            modelBuilder.Entity("WebInterface.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("OwnerGuestID");

                    b.HasKey("OrderID");

                    b.HasIndex("OwnerGuestID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebInterface.Models.Table", b =>
                {
                    b.Property<int>("TableID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Capacity");

                    b.HasKey("TableID");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("WebInterface.Models.Bill", b =>
                {
                    b.HasOne("WebInterface.Models.Guest", "Payer")
                        .WithMany()
                        .HasForeignKey("PayerGuestID");
                });

            modelBuilder.Entity("WebInterface.Models.Dish", b =>
                {
                    b.HasOne("WebInterface.Models.Order")
                        .WithMany("Finalized")
                        .HasForeignKey("OrderID");

                    b.HasOne("WebInterface.Models.Order")
                        .WithMany("Selected")
                        .HasForeignKey("OrderID1");

                    b.HasOne("WebInterface.Models.DishType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeDishTypeID");
                });

            modelBuilder.Entity("WebInterface.Models.Group", b =>
                {
                    b.HasOne("WebInterface.Models.Table", "Table")
                        .WithOne("CurrentGroup")
                        .HasForeignKey("WebInterface.Models.Group", "TableID");
                });

            modelBuilder.Entity("WebInterface.Models.Guest", b =>
                {
                    b.HasOne("WebInterface.Models.Group", "Group")
                        .WithMany("CurrentGuests")
                        .HasForeignKey("GroupID");
                });

            modelBuilder.Entity("WebInterface.Models.Ingredient", b =>
                {
                    b.HasOne("WebInterface.Models.Dish")
                        .WithMany("Ingredients")
                        .HasForeignKey("DishID");

                    b.HasOne("WebInterface.Models.DishType")
                        .WithMany("DefaultIngredients")
                        .HasForeignKey("DishTypeID");

                    b.HasOne("WebInterface.Models.IngredientType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeIngredientTypeID");
                });

            modelBuilder.Entity("WebInterface.Models.Order", b =>
                {
                    b.HasOne("WebInterface.Models.Guest", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerGuestID");
                });
#pragma warning restore 612, 618
        }
    }
}
